# Generated by Django 3.2.3 on 2021-06-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_blog_pic.jpg', upload_to='blog_pics'),
        ),
    ]
